=== Raszard/l2mobiusc6-PTBR/L2J_Mobius_C6_Interlude/dist/game/data/xsd/Quests.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="quest" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lvlMin">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="lvlMax">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="questType">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="entityName">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="contactNpc">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="restrictions">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="description">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
			  <xs:element name="class">
                <xs:complexType>
                  <xs:attribute name="val" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Raszard/l2mobiusc6-PTBR/L2J_Mobius_C6_Interlude/dist/game/data/Quests.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Quests.xsd">
  <quest id="1" name="Cartas de Amor">
    <lvlMin val="2" />
    <lvlMax val="5" />
    <questType val="3" />
    <entityName val="Gatekeeper Roxxy" />
    <contactNpc val="30048" />
    <restrictions val="Sem Requisitos" />
    <description val="Darin, um jovem na Talking Island, carrega uma paixão pela Teleportadora Roxxy, que não retribui seu afeto. Darin não é tão facilmente dissuadido, no entanto." />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="2" name="O que as Mulheres Querem">
    <lvlMin val="2" />
    <lvlMax val="5" />
    <questType val="3" />
    <entityName val="Teleportadora Mirabel" />
    <contactNpc val="30223" />
    <restrictions val="Elfo" />
    <description val="Arujian, um jovem da Elven Village, adora Magistrada Greenis de todo o coração, mas ninguém sabe se Greenis retribuirá seu afeto." />
    <class val="18-19-20-21-22-23-24-25-26-27-28-29-30-100-101-102-103-104-105" />
  </quest>
  <quest id="3" name="O Selo Será Quebrado?">
    <lvlMin val="16" />
    <lvlMax val="26" />
    <questType val="3" />
    <entityName val="School of Dark Arts" />
    <contactNpc val="30141" />
    <restrictions val="Elfo Sombrio" />
    <description val="O Humano traiu o segredo que manteve o Hierarca Mitraell selado por séculos! Ajude Tetrarca Talloth a quebrar o selo que prende Mitraell!" />
    <class val="31-32-33-34-35-36-37-38-39-40-41-42-43-106-107-108-109-110-111-112" />
  </quest>
  <quest id="4" name="Viva o Senhor Pa'Agrio!">
    <lvlMin val="2" />
    <lvlMax val="5" />
    <questType val="3" />
    <entityName val="" />
    <contactNpc val="30578" />
    <restrictions val="Orc" />
    <description val="Lorde Pa'agrio Kakai, o líder de todos os Orcs, está doente! os anciãos decidiram que cada tribo precisará entregar um presente a ele para garantir uma rápida recuperação." />
    <class val="44-45-46-47-48-49-50-51-52-113-114-115-116" />
  </quest>
  <quest id="5" name="Favor do Mineiro">
    <lvlMin val="2" />
    <lvlMax val="5" />
    <questType val="3" />
    <entityName val="" />
    <contactNpc val="30554" />
    <restrictions val="Sem Requisitos" />
    <description val="Os membros da Guilda do Pilar Cinzento estão trabalhando duro na Strip Mine. O mineiro Bolter está preocupado porque não há ninguém disponível para reunir os suprimentos de que a aldeia precisa." />
    <class val="53-54-55-56-57-117-118" />
  </quest>
  <quest id="101" name="Espada da Solidariedade">
    <lvlMin val="9" />
    <lvlMax val="16" />
    <questType val="3" />
    <entityName val="Ferreiro Altran" />
    <contactNpc val="30008" />
    <restrictions val="Humano" />
    <description val="A Espada da Solidariedade há muito simboliza a amizade entre Elfos e Humanos. o desaparecimento da espada coincidiu com a deterioração dessa amizade. o Grão-Mestre Roien está procurando um guerreiro para devolver a espada ao seu lugar de honra." />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="102" name="Febre do Sea of Spores">
    <lvlMin val="12" />
    <lvlMax val="18" />
    <questType val="3" />
    <entityName val="Mestre Cobendell" />
    <contactNpc val="30284" />
    <restrictions val="Elfo" />
    <description val="Sentinelas que estavam conduzindo experimentos no Sea of Spores ficaram com febre alta. Cavaleiro Sentinela Alberius está procurando alguém para visitar o Mestre Cobendell para obter a cura." />
    <class val="18-19-20-21-22-23-24-25-26-27-28-29-30-100-101-102-103-104-105" />
  </quest>
  <quest id="103" name="Espírito de Artesão">
    <lvlMin val="10" />
    <lvlMax val="17" />
    <questType val="3" />
    <entityName val="Celebrante Abissal Cecktinon" />
    <contactNpc val="30307" />
    <restrictions val="Elfo Sombrio" />
    <description val="Karrod da Dark Elven Village é o melhor de todos os Ferreiros Elfos. Apesar de sua incrível habilidade, ele ainda não pode refinar minério de oriharukon. Convoque um Anão Warsmith para descobrir o segredo!" />
    <class val="31-32-33-34-35-36-37-38-39-40-41-42-43-106-107-108-109-110-111-112" />
  </quest>
  <quest id="104" name="Espírito dos Espelhos">
    <lvlMin val="10" />
    <lvlMax val="15" />
    <questType val="3" />
    <entityName val="" />
    <contactNpc val="30017" />
    <restrictions val="Humano" />
    <description val="Três Espíritos do Espelho escaparam do laboratório do Magistrado Gallint na Talking Island! Capture e sele esses espíritos!" />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="105" name="Combate com os Orcs">
    <lvlMin val="10" />
    <lvlMax val="15" />
    <questType val="3" />
    <entityName val="" />
    <contactNpc val="30218" />
    <restrictions val="Elfo" />
    <description val="Orcs Kaboo das Montanhas Sombrias invadiram a Elven Forest novamente. Ajude a Sentinela Kendell e os Elfos Fighters a derrotar os invasores e tomar a cabeça do Capitão Orc!" />
    <class val="18-19-20-21-22-23-24-25-26-27-28-29-30-100-101-102-103-104-105" />
  </quest>
  <quest id="106" name="Verdade Esquecida">
    <lvlMin val="10" />
    <lvlMax val="15" />
    <questType val="3" />
    <entityName val="Celebrante Abissal Kartia" />
    <contactNpc val="30358" />
    <restrictions val="Elfo Sombrio" />
    <description val="O infame Orc Brigand roubou as Revelações de Kaysha! Recupere este documento vital para garantir o futuro de todos os Elfos Sombrios!" />
    <class val="31-32-33-34-35-36-37-38-39-40-41-42-43-106-107-108-109-110-111-112" />
  </quest>
  <quest id="107" name="Punição Impiedosa">
    <lvlMin val="12" />
    <lvlMax val="16" />
    <questType val="3" />
    <entityName val="Centurião Parugon" />
    <contactNpc val="30568" />
    <restrictions val="Orc" />
    <description val="O traidor exilado Baranka planeja derrubar o reino dos Orcs! Revele sua trama perversa e destrua-o! Dejakar Oroka!" />
    <class val="44-45-46-47-48-49-50-51-52-113-114-115-116" />
  </quest>
  <quest id="108" name="Confusão, Queda, Barulho de Diamante">
    <lvlMin val="10" />
    <lvlMax val="14" />
    <questType val="3" />
    <entityName val="Comerciante Reep" />
    <contactNpc val="30523" />
    <restrictions val="Anão" />
    <description val="O Diamante Estrela é um dos apenas 12 em todo o continente! os Anões estão planejando um Confusão, Qued Barulho de Diamante!" />
    <class val="53-54-55-56-57-117-118" />
  </quest>
  <quest id="151" name="Cura para Febre">
    <lvlMin val="15" />
    <lvlMax val="21" />
    <questType val="3" />
    <entityName val="Talking Island, Western Territory" />
    <contactNpc val="30050" />
    <restrictions val="Sem Requisitos" />
    <description val="Os alunos da Einhovants School of Magic estão com uma febre misteriosa. o professor deles, Elias, está bastante preocupado." />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="152" name="Estilhaços de Golem">
    <lvlMin val="10" />
    <lvlMax val="17" />
    <questType val="3" />
    <entityName val="Ferreiro Altran" />
    <contactNpc val="30035" />
    <restrictions val="Sem Requisitos" />
    <description val="O telhado do Einhasad Temple desabou! Ajude o Magistrado Harrys a restaurar o templo!" />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="153" name="Entregar Mercadorias">
    <lvlMin val="2" />
    <lvlMax val="5" />
    <questType val="3" />
    <entityName val="" />
    <contactNpc val="30041" />
    <restrictions val="Sem Requisitos" />
    <description val="A carga que se presumia perdida em um naufrágio recente foi recuperada. Ajude o guarda Arnold a entregar a carga aos destinatários." />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="154" name="Sacrifício ao Mar">
    <lvlMin val="2" />
    <lvlMax val="7" />
    <questType val="3" />
    <entityName val="Talking Island, Eastern Territory" />
    <contactNpc val="30312" />
    <restrictions val="Sem Requisitos" />
    <description val="O Faroleiro Rockswell planeja um ritual de sacrifício para acalmar as tempestades que assolam a ilha. Desta vez, ele pretende usar uma boneca em vez de uma virgem viva." />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="155" name="Encontrar Senhor Windawood">
    <lvlMin val="3" />
    <lvlMax val="6" />
    <questType val="3" />
    <entityName val="Obelisk of Victory" />
    <contactNpc val="30042" />
    <restrictions val="Sem Requisitos" />
    <description val="Chegou uma carta importante para Senhor Colin Windawood, o Cônsul da Talking Island. Senhor Windawood, mais provável de ser descoberto em um passeio do que em seu escritório, não o viu. Encontre Senhor Windawood e entregue a carta a ele." />
    <class val="0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-88-89-90-91-92-93-94-95-96-97-98-99" />
  </quest>
  <quest id="156" name="Amor Milenar">
    <lvlMin val="15" />
    <lvlMax val="19" />
    <questType val="3" />
    <entityName val="???" />
    <contactNpc val="30368" />
    <restrictions val="Sem Requisitos" />
